### ISSUE TITLE
Crash BOT

### ISSUE THREAD

**Issue by Cripix** [drew73197/Discord-Report#1]
Hi !
When I try to send a report the bot and it gives me this as error:

![capture](https://user-images.githubusercontent.com/30194894/29281936-2860a726-8121-11e7-8213-ca4172f999e6.PNG)

Is it possible to solve it?

Thanks !

**Comment by drew73197** [comment]
I'll check it out give me a minute!

**Comment by drew73197** [comment]
So looking at the error you received it seems to me that inside of your config.js you haven't set this correctly
adminRole: "Admin", // The role name of people that should be able to use the bot
If admin isn't the role of who should be notified of reports then change it to what it should be, also as far as I'm aware capitalization matters too!

**Comment by Cripix** [comment]
So I have to put something like @Admin?

**Comment by drew73197** [comment]
You don't wanna put the @ there just leave the role name it'll automatically do the @Admin or whatever the role name is, just make sure the role name is correct, if that doesn't solve it let me know!

**Comment by drew73197** [comment]
Did you figure it out?

**Comment by Cripix** [comment]
Yes it works!

Thanks <3

**Comment by drew73197** [comment]
No worries dude, thanks for using my project!
