### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by mrc4tt** [drew73197/Discord-Report#2]
hi.

I have some issues with the plugin.

It don't post, about the report has been submitted. and the issues is. it has access to mySQL database + remote connection is open... and it wont post errors. what 2 do?
@drew73197

**Comment by drew73197** [comment]
Sorry I haven’t been active with this project the last update I put through broke it and I never got around to fixing it I can get you the last working version if you want

**Comment by drew73197** [comment]
https://github.com/drew73197/Discord-Report/tree/ca3a18c5543c80257cb27423cdc8d80643594260
