### ISSUE TITLE
(DOUBT)

### ISSUE THREAD

**Issue by chulicoxd** [drew73197/Discord-Report#3]
Could this add-on be used for cs go? since I have a calladmin discord but it does not send exactly the message that I would like, I would love to get a message with the person who reported and the steam id of the supposed "hacker", sorry but in the forum does not let me ask, that's why The only option is to ask here.

**Comment by drew73197** [comment]
Sorry for the super late reply, but as long as you are using sourcemod on your server I do not know why you couldn't. All the smx plugin does is throw some data in a database, then the bot reads the database every so often. As long as you or someone can get the plugin working right in the server everything else will work out of the box. iirc my last update broke everything so download an older version of the code, and you should be good!

**Comment by drew73197** [comment]
https://github.com/drew73197/Discord-Report/tree/ca3a18c5543c80257cb27423cdc8d80643594260
this is the working code!
